"""add remnawave_uuid to Client

Revision ID: 21632226787d
Revises: 9a4fbc0df049
Create Date: 2026-04-13 11:31:51.275983

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '21632226787d'
down_revision: Union[str, Sequence[str], None] = '9a4fbc0df049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('remnawave_uuid', sa.UUID(), nullable=False))
    op.create_unique_constraint('uq_client_remnawave_uuid', 'client', ['remnawave_uuid'])
    op.drop_constraint(op.f('operation_client_id_fkey'), 'operation', type_='foreignkey')
    op.create_foreign_key(None, 'operation', 'client', ['client_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operation', type_='foreignkey')
    op.create_foreign_key(op.f('operation_client_id_fkey'), 'operation', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_client_remnawave_uuid', 'client', type_='unique')
    op.drop_column('client', 'remnawave_uuid')
    # ### end Alembic commands ###
