"""allow null client_id in Operation

Revision ID: 7f50fde7e046
Revises: 21632226787d
Create Date: 2026-04-20 20:28:03.307845

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f50fde7e046'
down_revision: Union[str, Sequence[str], None] = '21632226787d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('operation_client_id_fkey'), 'operation', type_='foreignkey')
    op.create_foreign_key('operation_client_id_fkey', 'operation', 'client', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('operation_client_id_fkey', 'operation', type_='foreignkey')
    op.create_foreign_key(op.f('operation_client_id_fkey'), 'operation', 'client', ['client_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('operation', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
