"""add indexes

Revision ID: f53a0fdf179c
Revises: 7f50fde7e046
Create Date: 2026-05-13 20:01:57.966219

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f53a0fdf179c'
down_revision: Union[str, Sequence[str], None] = '7f50fde7e046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_client_created_at', 'client', ['created_at'], unique=False)
    op.create_index('ix_client_expires_at', 'client', ['expires_at'], unique=False)
    op.create_index('ix_client_status_created_at', 'client', ['status', 'created_at'], unique=False)
    op.create_index('ix_operation_client_id', 'operation', ['client_id'], unique=False)
    op.create_index('ix_operation_created_at', 'operation', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operation_created_at', table_name='operation')
    op.drop_index('ix_operation_client_id', table_name='operation')
    op.drop_index('ix_client_status_created_at', table_name='client')
    op.drop_index('ix_client_expires_at', table_name='client')
    op.drop_index('ix_client_created_at', table_name='client')
    # ### end Alembic commands ###
